export const fieldsSignIn = [
  {
    type: "email",
    id: "email",
    name: "email",
    label: "Почта",
    placeholder: "example@mail.com",
    required: true,
  },
  {
    type: "text",
    id: "login",
    name: "login",
    label: "Логин",
    placeholder: "Логин",
    required: true,
  },
  {
    type: "text",
    id: "name",
    name: "first_name",
    label: "Имя",
    placeholder: "Ваше имя",
    required: true,
  },
  {
    type: "text",
    id: "secondname",
    name: "second_name",
    label: "Фамилия",
    placeholder: "Фамилия",
  },
  {
    type: "phone",
    id: "phone",
    name: "phone",
    label: "Телефон",
    placeholder: "Телефон",
  },
  {
    type: "password",
    id: "password",
    name: "newPassword",
    label: "Пароль",
    placeholder: "Пароль",
  },
  {
    type: "password",
    id: "password-2",
    name: "newPassword",
    label: "Пароль(еще раз)",
    placeholder: "Пароль(еще раз)",
    value: "feneqn",
    error: "Error",
  },
];
