export const fieldsForProfile = [
  {
    type: "email",
    id: "email",
    name: "email",
    label: "Почта",
    placeholder: "Почта",
    value: "ivan@example.com",
    inline: true,
    disabled: true,
  },
  {
    type: "text",
    id: "login",
    name: "login",
    label: "Логин",
    placeholder: "Логин",
    value: "ivan123",
    inline: true,
    disabled: true,
  },
  {
    type: "text",
    id: "first_name",
    name: "first_name",
    label: "Имя",
    placeholder: "Имя",
    value: "Иван",
    inline: true,
    disabled: true,
  },
  {
    type: "text",
    id: "second_name",
    name: "second_name",
    label: "Фамилия",
    placeholder: "Фамилия",
    value: "Иванов",
    inline: true,
    disabled: true,
  },
  {
    type: "text",
    id: "name",
    name: "name",
    label: "Имя в чате",
    placeholder: "Имя в чате",
    value: "Иван",
    inline: true,
    disabled: true,
  },
  {
    type: "phone",
    id: "phone",
    name: "phone",
    label: "Телефон",
    placeholder: "Телефон",
    value: "+7 (123) 456-78-90",
    inline: true,
    disabled: true,
  },
];
