export const mockChats = [
  {
    id: 1,
    name: "Андрей",
    text: "Привет! Как дела?",
    time: "10:30",
    count: 2,
  },
  {
    id: 2,
    name: "Мария",
    text: "Завтра встреча в 15:00",
    time: "09:15",
    count: 1,
  },
  {
    id: 3,
    name: "Иван Петров",
    text: "Отправил документы",
    time: "Вчера",
    count: 5,
  },
  {
    id: 4,
    name: "Рабочая группа",
    text: "Елена: Готовы к презентации?",
    time: "Вчера",
  },
  {
    id: 5,
    name: "Кафе 'Уют'",
    text: "Ваш заказ готов к выдаче",
    time: "Пн",
  },
  {
    id: 6,
    name: "Ольга",
    text: "Спасибо за помощь!",
    time: "Ср",
  },
  {
    id: 7,
    name: "Дмитрий",
    text: "Когда сможем созвониться?",
    time: "15 мая",
    count: 3,
  },
  {
    id: 8,
    name: "Книжный клуб",
    text: "Обсуждение новой книги перенесено",
    time: "12 мая",
  },
];
export const mockMessages = [
  {
    id: 1,
    text: "Привет! Как дела?",
    time: "10:30",
    isOutgoing: false,
    isRead: true,
  },
  {
    id: 2,
    text: "Привет! Все отлично, спасибо! А у тебя как?",
    time: "10:31",
    isOutgoing: true,
    isRead: true,
  },
  {
    id: 3,
    text: "Тоже все хорошо. Что нового?",
    time: "10:32",
    isOutgoing: false,
    isRead: true,
  },
  {
    id: 4,
    text: "Работаю над новым проектом, очень интересный функционал",
    time: "10:33",
    isOutgoing: true,
    isRead: true,
  },
  {
    id: 5,
    text: "Здорово! Расскажешь поподробнее?",
    time: "10:34",
    isOutgoing: false,
    isRead: true,
  },
  {
    id: 6,
    text: "Конечно! Это мессенджер с современным интерфейсом",
    time: "10:35",
    isOutgoing: true,
    isRead: false,
  },
  {
    id: 7,
    text: "Звучит интересно. Жду деталей!",
    time: "10:36",
    isOutgoing: false,
    isRead: false,
  },
];
